config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "users#new"
  get "/auth/github", as: :github_login
  get "/auth/:provider/callback" => "sessions#create"
  get "/signout" => "sessions#destroy", as: :github_logout

  resources :users, only: [:new, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ActiveRecord::Base

  def self.create_with_omniauth(auth)
    where(uid: auth.uid).first_or_create do |user|
      user.uid = auth.uid
      user.name = auth.info.name
      user.username = auth.info.nickname
      user.token = auth.credentials.token
      user.avatar = auth.info.image
      user.email = auth.info.email
    end
  end

  def self.service
    @service ||= GithubService.new()
  end

  # def self.find_user(params)
  #   service.
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    if user = User.create_with_omniauth(request.env["omniauth.auth"])
      session[:user_id] = user.id
      flash[:success] = "Successfully signed in #{user.name}!"
      redirect_to user_path(user)
    else
      flash[:danger] = "Failed to successfully sign in. :("
      redirect_to
    end
  end

  def destroy
    session.clear
    flash[:success] = "Successfully signed out!"
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new

  end

  def show
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Zack's Apicurious
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all'
    %link{href: "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css", rel: "stylesheet", integrity: "sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7", crossorigin: "anonymous"}
    = javascript_include_tag 'application'
  %body
    = render partial: 'shared/nav_bar'
    - flash.each do |type, message|
      .alert.text-center{class: "alert-#{type}"}
        %button.close{"data-dismiss": "alert", type: "button"} x
        %strong
          = message
    =yield

app/views/shared/_nav_bar.html.haml
%nav.navbar.navbar-default{role: "navigation"}
  .navbar-header
    %button.navbar-toggle{"data-target": "#bs-example-navbar-collapse-1", "data-toggle": "collapse", type: "button"}
      %span.sr-only Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    %a.navbar-brand{href: "/"} Zack's ApiCurious
  .collapse.navbar-collapse#bs-example-navbar-collapse-1
    %ul.nav.navbar-nav
      - if current_user
        %li
          = link_to 'Account', user_path(current_user)
        %li
          = link_to 'Activity', "#" #make this a dropdown to use with followed_user_activity and my_activity
    %ul.nav.navbar-nav.navbar-right
      - if current_user
        %li
          = link_to 'Logout of GitHub', github_logout_path
      - else
        %li
          = link_to 'Login with GitHub', github_login_path

app/views/users/new.html.haml
- if current_user
  %h3.text-center= "Welcome #{current_user.name}!"
- else
  %h3.text-center= "Welcome to Zack's ApiCurious App!"
  %h3.text-center= "Login above to administer your GitHub Account!"

app/views/users/show.html.haml
.container.col-md-5.col-lg-6.responsive-image= image_tag(@user.avatar)
.container.col-md-5.col-lg-6
  %h3= @user.name
  %h3= @user.username
  %h3= @user.email